# -*- coding: utf-8 -*-
"""team1_pp project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6kS85VkxpwcXnY1ouy95kloLMYn1wwy
"""

class FootwearManagementSystem:
    def __init__(self):
        self.products = []  # List to store product details
        self.inventory = {}  # Dictionary to store product inventory
        self.wishlist = set()  # Set to store wishlist items

    def add_product(self, product_name, price, size, color):
        product = {'name': product_name, 'price': price, 'size': size, 'color': color}
        self.products.append(product)
        self.inventory[product_name] = 0

    def update_inventory(self, product_name, quantity):
        if product_name in self.inventory:
            self.inventory[product_name] += quantity
        else:
            print("Product not found in inventory.")

    def add_to_wishlist(self, product_name):
        self.wishlist.add(product_name)

    def remove_from_wishlist(self, product_name):
        self.wishlist.discard(product_name)

    def display_products(self):
        print("Available Products:")
        for product in self.products:
            print(f"Name: {product['name']}, Price: ${product['price']}, Size: {product['size']}, Color: {product['color']}")

    def display_inventory(self):
        print("Current Inventory:")
        for product_name, quantity in self.inventory.items():
            print(f"{product_name}: {quantity}")

    def display_wishlist(self):
        print("Wishlist Items:")
        for item in self.wishlist:
            print(item)


# Example usage
if __name__ == "__main__":
    system = FootwearManagementSystem()

    system.add_product("Sneakers", 50, 9, "Black")
    system.add_product("Sandals", 30, 8, "Brown")

    system.update_inventory("Sneakers", 10)
    system.update_inventory("Sandals", 5)

    system.add_to_wishlist("Sneakers")
    system.add_to_wishlist("Heels")

    print("Product List:")
    system.display_products()

    print("\nInventory:")
    system.display_inventory()

    print("\nWishlist:")
    system.display_wishlist()